Fix compatibility with StaticArrays
https://github.com/JuliaArrays/FillArrays.jl/pull/219 broke compatibility with static arrays and thus downstream tests:

```julia
  Got exception outside of a @test
  LoadError: MethodError: +(::StaticArraysCore.SVector{2, Float64}, ::FillArrays.Fill{Float64, 1, Tuple{Base.OneTo{Int64}}}) is ambiguous. Candidates:
    +(a::AbstractArray, b::FillArrays.AbstractFill) in FillArrays at /home/runner/.julia/packages/FillArrays/VUZcr/src/fillalgebra.jl:242
    +(a::StaticArraysCore.StaticArray, b::AbstractArray) in StaticArrays at /home/runner/.julia/packages/StaticArrays/4WE4t/src/linalg.jl:14
  Possible fix, define
    +(::StaticArraysCore.StaticArray, ::FillArrays.AbstractFill)
```

https://github.com/SciML/OrdinaryDiffEq.jl/actions/runs/4444632992/jobs/7803006749?pr=1908#step:6:920

But it's not clear that the change to these operators was even necessary for anything.